---
- hosts: localhost
  connection: local
  gather_facts: false
  # vars:
  tasks:
    - name: "Remove GitLab Project if it is requiered"
      vars:
        gitlab_project: "casc_{{ user_item.gitlab_user }}"
      community.general.gitlab_project:
        state: absent
        api_url: "{{ gitlab_api_url }}"
        validate_certs: "{{ gitlab_validate_certs }}"
        api_token: "{{  gitlab_api_token }}"
        name: "{{ gitlab_project }}"
        group: "{{ gitlab_group if (gitlab_group is defined and gitlab_group is not regex('^\\s*$')) }}{{ ('/' + gitlab_subgroup) if (gitlab_subgroup is defined and gitlab_subgroup is not regex('^\\s*$')) else '' }}"
      when: user_item.delete_previous_repo | default(false)
      loop: "{{ users }}"
      loop_control:
        loop_var: user_item

    - name: Apply gitlab_setup tasks
      vars:
        gitlab_project: "casc_{{ user_item.gitlab_user }}"
      ansible.builtin.include_tasks:
        file: gitlab_setup.yml
        apply:
          tags:
            - git-init
            - filetree_create
            - git-push
            - git-branches
      loop: "{{ users }}"
      loop_control:
        loop_var: user_item

    - name: Add a user to a GitLab Project
      community.general.gitlab_project_members:
        api_url: "{{ gitlab_api_url }}"
        validate_certs: "{{ gitlab_validate_certs }}"
        api_token: "{{  gitlab_api_token }}"
        project: "casc_{{ user_item.gitlab_user }}"
        gitlab_user: "{{ user_item.gitlab_user }}"
        access_level: maintainer
        state: present
      loop: "{{ users }}"
      loop_control:
        loop_var: user_item

#    - name: Sending emails to users
#      community.general.mail:
#        host: smtp.gmail.com
#        port: 587
#        username: "{{ user_gmail }}"
#        password: "{{ pass_gmail }}"
#        to: "{{ user_item.email }}"
#        subject: CasC instructions
#        body: "Your repository in gitlab is {{ gitlab_api_url }}/{{ gitlab_group }}/{{ gitlab_subgroup }}/casc_{{ user_item.gitlab_user }}. Follow the instructions which you have in README."
#      loop: "{{ users }}"
#      loop_control:
#        loop_var: user_item
...
