---
controller_credentials:
  - name: "TOWER-Git-Credential"
    description: ""
    credential_type: "Source Control"
    organization: "TOWER-ORG"
    inputs:
      password: "{{ vault_git_password }}"
      username: aap-demo

...
