---
controller_templates:
  - name: Recursive Job Template Multi File
    description: !unsafe
    organization: Recursive Workflows
    project: Controller CasC Examples Project
    inventory: Recursive Workflows Inventory
    playbook: playbooks/recursive-playbook-multi-file.yaml
    scm_branch: ""
    forks: 0
    limit: ""
    verbosity: 0
    job_type: run
    job_slice_count: 1
    use_fact_cache: false
    credentials:
      - AAP Self Connection
      - Recursive Workflows Credential
    allow_simultaneous: true
    ask_scm_branch_on_launch: false
    ask_diff_mode_on_launch: false
    ask_tags_on_launch: false
    ask_skip_tags_on_launch: false
    ask_job_type_on_launch: false
    ask_verbosity_on_launch: false
    ask_variables_on_launch: true
    ask_inventory_on_launch: false
    ask_limit_on_launch: false
    ask_credential_on_launch: true
    ask_execution_environment_on_launch: false
    ask_labels_on_launch: false
    ask_forks_on_launch: false
    ask_job_slice_count_on_launch: false
    ask_timeout_on_launch: false
    ask_instance_groups_on_launch: false
    extra_vars: ""
    job_tags: ""
    force_handlers: false
    skip_tags: ""
    start_at_task: ""
    timeout: 0
    execution_environment: casc-examples
    host_config_key: ""
    survey_enabled: false
    become_enabled: false
    diff_mode: false
    webhook_service: ""
    prevent_instance_group_fallback: false
...
