---
# controller_settings:
#   - settings:
#       TOWER_URL_BASE: "https://meetup-aap25-controller.iam.lab"
#       INSIGHTS_TRACKING_STATE: "false"
#       PENDO_TRACKING_STATE: "off"
#       AWX_TASK_ENV:
#         GIT_SSL_NO_VERIFY: 'True'
#         HOME: /var/lib/awx
#       CUSTOM_LOGIN_INFO: Configuration as Code Migration Test
...
