---
controller_schedules:
  - name: Cleanup Expired Sessions
    description: !unsafe Cleans out expired browser sessions
    enabled: true
    unified_job_template: Cleanup Expired Sessions
    dtstart: "2025-10-31T20:11:06Z"
    dtend: ""
    timezone: UTC
    rrule: DTSTART:20231213T081750Z RRULE:FREQ=WEEKLY;INTERVAL=1
    scm_branch: ""
    forks: 0
    job_slice_count: 0
    timeout: 0
    job_type: ""
    job_tags: ""
    skip_tags: ""
    limit: ""
    verbosity: 0
...
