---
controller_credentials:
  - name: "CONTROLLER-Git-Credential"
    description: ""
    credential_type: "Source Control"
    organization: "CONTROLLER-ORG"
    inputs:
      password: "{{ vault_git_password }}"
      username: aap-demo

...
