---
controller_credentials:
  - name: "AWX-Git-Credential"
    description: ""
    credential_type: "Source Control"
    organization: "AWX-ORG"
    inputs:
      password: "{{ vault_git_password }}"
      username: aap-demo

...
