---
controller_credentials:
  - name: "AWX-HUB-Cluster-Kubeconfig"
    description: ""
    credential_type: "Kubeconfig"
    organization: "AWX-ORG"
    inputs:
      kube_config: "{{ vault_hub_kubeconfig_file_content }}"

...
