= Import the configuration into the Ansible Controller
include::_attributes.adoc[]

== Import the configuration

Once all the configuration files has been organized and the credentials have been filled in, it can be imported into the Ansible Controller, as shown below.

=== Export all the variables to be used in the next steps

The following variables will be used in the next steps, and are exported using `read` to avoid having sensitive information in the command history of the server.

[IMPORTANT]
====
These variables are undefined when you close your terminal session, so they need to be populated each time you open a new terminal.

The shell that is expected to be used to run the snippet below is `bash`.
====

NOTE: The `Vault Password` variable used here should be the same as the one used previously in the exportation process (see xref:020-export.adoc#Export[Export data from AWX/Tower]). It is defined here again only for completeness.

[.console-input]
[source,console]
----
read -e -p ">>> User Name: " CONTROLLER_USERNAME
read -e -p ">>> Password: " -s CONTROLLER_PASSWORD
read -e -p ">>> Ansible Controller Hostname: " CONTROLLER_HOSTNAME
read -e -p ">>> Validate Certs (yes/no): " -i no CONTROLLER_VALIDATE_CERTS
read -e -p ">>> Is AAP (yes/no): " -i yes IS_AAP
read -e -p ">>> Have Constructed Inventories (yes/no): " -i yes HAVE_CONSTRUCTED
read -e -p ">>> Vault Password: " VAULT_PASSWORD
----

== Customize the Ansible Controller connection

The next step is to configure the files to let the playbooks to connect to the Ansible Controller instance:

[.console-input]
[source,console]
----
cat > my_vars/vault-controller.yaml <<EOF
---
# Ansible Controller
vault_controller_username: "${CONTROLLER_USERNAME}"
vault_controller_password: "${CONTROLLER_PASSWORD}"
vault_controller_hostname: "${CONTROLLER_HOSTNAME}"
vault_controller_validate_certs: ${CONTROLLER_VALIDATE_CERTS}
is_aap: ${IS_AAP}
have_constructed: ${HAVE_CONSTRUCTED}
...
EOF
----

As this file is containing sensitive information, it needs to be encrypted using `ansible-vault`:

NOTE: Similarly as above, The `.vault-password` file used here should be the same as the one used previously in the exportation process (see xref:020-export.adoc#Export[Export data from AWX/Tower]). It is created here again only for completeness.

[.console-input]
[source,console]
----
echo ${VAULT_PASSWORD} > .vault-password
chmod 0600 .vault-password
ansible-vault encrypt --vault-password-file .vault-password my_vars/vault-controller.yaml
----

== Customize the Instance Groups

The file `configs/controller/current_instance_groups.yaml` contains the Instance Group definition for the AWX instance. This file is useless and will generate errors if it's not customized or removed, as the target Ansible Controller instance will run in different Instances. So, this file can be customized to define the new and needed Instance Groups using the new Instances, or can be deleted to let the firsts imports to work properly:

.Exported Instance Group
[.console-input]
[source,console]
----
$ cat configs/controller/current_instance_groups.yaml     
---
controller_instance_groups:
  - name: "tower"
    policy_instance_minimum: "0"
    policy_instance_percentage: "100"
    instances:
      - "awx"
...
----

.Remove the Instance Group file
[.console-input]
[source,console]
----
rm configs/controller/current_instance_groups.yaml
----

== Run the import process

[.console-input]
[source,console]
----
\
ansible-navigator run playbooks/config-controller-filetree.yaml \
  -i localhost, \
  -m stdout \
  --eei quay.io/automationiberia/casc/ee-casc:summit24 \
  --eev /tmp/:/tmp/ \
  -e @my_vars/vault-controller.yaml \
  -e @my_vars/vaulted-credentials.yaml \
  -e @my_vars/paths-controller.yaml \
  --vault-password-file .vault-password \
  -e '{
        ansible_async_dir: /home/runner/.ansible_async/ 
      }'
----
