= Next-Gen Infrastructure: Migrating to Ansible Controller with GitOps
// :page-layout: home
// :!sectids:

When migrating or moving from one infrastructure to another, the method explained below offers another approach to transfer the contents of an old AWX instance, Ansible Tower or even an Automation Controller to any other instance of an Automation Controller. Although there may be a learning curve if you're not yet familiar with GitOps or DevOps methodologies, this method sets a strong foundation for future migrations and seamless transitions between infrastructures.

This workshop not only covers the migration process but also introduces the powerful practice of Configuration as Code (CaC) for Ansible Controller. By implementing CaC, you can efficiently manage your configuration in a GitOps manner, ensuring consistency, version control, and automation.

This session is designed to be the first step for those who have not yet adopted CaC. Additional steps for establishing a full GitOps workflow can be found at https://automationiberia.github.io/controller-casc-cd[https://automationiberia.github.io/controller-casc-cd].

[.tiles.browse]
== Browse modules

[.tile]
* xref:020-export.adoc[Export data from AWX/Tower]
* xref:021-organize.adoc[Organize the data]
* xref:022-fill-credentials.adoc[Fill in the sensitive data]
* xref:023-import.adoc[Apply the configuration to the Ansible Controller]
