= Welcome to the Workshop/Demo to migrate and AWX/Tower to Automation Controller using a Continuous Deployment approach
// :page-layout: home
// :!sectids:

If there's the need of migrating the contents of an old instance of AWX or Ansible Tower to a new instance of Ansible Controller, the easiest way to do is explained below. In addition to the migration itself, it introduces to the usage of Configuration as Code applied to the Ansible Controller, which let's managing it's configuration in a GitOps way. The current workshop is the first step to be done if the Configuration as Code still doesn't exist, and the following steps for the GitOps are available at https://automationiberia.github.io/controller-casc-cd[https://automationiberia.github.io/controller-casc-cd].

[.tiles.browse]
== Browse modules

[.tile]
* xref:020-export.adoc[Export data from AWX/Tower]
* xref:021-organize.adoc[Organize the data]
* xref:022-fill-credentials.adoc[Fill in the sensitive data]
* xref:023-import.adoc[Apply the configuration to the Ansible Controller]
