---
controller_credentials:
  - name: "CONTROLLER-Git-Credential"
    description: ""
    credential_type: "Source Control"
    organization: "CONTROLLER-ORG"
    inputs:
      username: awx-git-cred-temp

...
