---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--ignore-certs"
dependencies:
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements-aap24.yml
  system: |
    git-core [platform:rpm]
    python3.9-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    python-unversioned-command [platform:rpm]
    unzip [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pyOpenSSL
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
options:
  package_manager_path: /usr/bin/dnf

additional_build_files:
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - RUN /usr/bin/dnf install -y git
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
      # - RUN alternatives --set python /usr/bin/python3
...
# ---
# version: 1
# build_arg_defaults:
#   ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--ignore-certs"
#   EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest'
# ansible_config: 'ansible.cfg'
# dependencies:
#   galaxy: requirements.yml
#   python: requirements.txt
#   system: bindep.txt
# additional_build_steps:
#   append:
#     - RUN alternatives --set python /usr/bin/python3
# ...
