---
controller_projects:
  - name: "TOWER-Project-Inventory"
    description: ""
    organization: "TOWER-ORG"
    scm_type: "git"
    scm_url: "http://gitlab.bcnconsulting.com/automation-everywhere/simple-ansible-inventory.git"
    scm_credential: "TOWER-Git-Credential"
    scm_branch: ""
    scm_clean: "True"
    scm_delete_on_update: "True"
    scm_update_on_launch: "False"
    scm_update_cache_timeout: "0"
    allow_override: "False"
    timeout: 0
...
