---
controller_credentials:
  - name: "AAP Self Connection"
    description: ""
    credential_type: "Red Hat Ansible Automation Platform"
    organization: "Recursive Workflows"
    inputs:
      host: "https://meetup-aap25-gateway/"
      username: "admin"
      password: "redhat00"
      verify_ssl: false

...
