---
controller_workflows:
  - name: CONTROLLER-WF
    description: !unsafe
    organization: CONTROLLER-ORG
    simplified_workflow_nodes:
      - identifier: PROJECT_UPDATE
        workflow_job_template: CONTROLLER-WF
        unified_job_template: CONTROLLER-Project
        limit: ""
        organization: CONTROLLER-ORG
        all_parents_must_converge: "False"
        success_nodes:
          - JOB_TEMPLATE_1
      - identifier: JOB_TEMPLATE_1
        workflow_job_template: CONTROLLER-WF
        unified_job_template: CONTROLLER-Helloworld
        verbosity: "0"
        limit: ""
        organization: CONTROLLER-ORG
        all_parents_must_converge: "False"
        always_nodes:
          - JOB_TEMPLATE_2
      - identifier: JOB_TEMPLATE_2
        workflow_job_template: CONTROLLER-WF
        unified_job_template: CONTROLLER-Read-Only-Playbook
        limit: ""
        organization: CONTROLLER-ORG
        all_parents_must_converge: "False"
        success_nodes:
          - JOB_TEMPLATE_4
        failure_nodes:
          - JOB_TEMPLATE_3
      - identifier: JOB_TEMPLATE_3
        workflow_job_template: CONTROLLER-WF
        unified_job_template: CONTROLLER-Helloworld
        verbosity: "0"
        limit: ""
        organization: CONTROLLER-ORG
        all_parents_must_converge: "False"
      - identifier: JOB_TEMPLATE_4
        workflow_job_template: CONTROLLER-WF
        unified_job_template: CONTROLLER-Read-Only-Playbook
        limit: ""
        organization: CONTROLLER-ORG
        all_parents_must_converge: "False"
    ask_variables_on_launch: "False"
    allow_simultaneous: "False"
    scm_branch: ""
    limit: ""
    ask_limit_on_launch: false
    ask_inventory_on_launch: false
    webhook_service: gitlab
    extra_vars: ""
    survey_enabled: false
...
