---
controller_workflows:
  - name: RecursiveWorkflowsMainWorkflow
    description: !unsafe
    organization: Recursive Workflows
    simplified_workflow_nodes:
      - identifier: b0f1be76-649a-4a21-9e4b-c5ca652bda95
        workflow_job_template: RecursiveWorkflowsMainWorkflow
        unified_job_template: RecursiveWorkflowsWorkflow2
        limit: ""
        organization: Recursive Workflows
        all_parents_must_converge: "False"
      - identifier: 31df88f5-d6e4-45ec-b4fa-60bbe91b6600
        workflow_job_template: RecursiveWorkflowsMainWorkflow
        unified_job_template: RecursiveWorkflowsWorkflow1
        limit: ""
        organization: Recursive Workflows
        all_parents_must_converge: "False"
        success_nodes:
          - b0f1be76-649a-4a21-9e4b-c5ca652bda95
    ask_variables_on_launch: "False"
    allow_simultaneous: "False"
    scm_branch: ""
    limit: ""
    ask_limit_on_launch: false
    ask_inventory_on_launch: false
    webhook_service: ""
    extra_vars: ""
    survey_enabled: false
...
