---
controller_credentials:
  - name: CONTROLLER-Git-Credential
    description: !unsafe
    credential_type: Source Control
    organization: CONTROLLER-ORG
    inputs:
      username: awx-git-cred-temp
...
