---
controller_credentials:
  - name: CONTROLLER-Machine Credential
    description: !unsafe Testing Machine Credential
    credential_type: Machine
    organization: CONTROLLER-ORG
    inputs:
      password: '{{ vaulted_controller_credentials_controller_machine_credential_password }}'
      username: admin
...
