---
- name: Export Automation Controller Configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    assign_galaxy_credentials_to_org: false
    controller_state: present
    aap_hostname: "{{ vault_controller_hostname }}"
    aap_username: "{{ vault_controller_username }}"
    aap_password: "{{ vault_controller_password }}"
    aap_validate_certs: "{{ vault_controller_validate_certs }}"
  pre_tasks:
    - name: "Setup authentication (block)"
      no_log: "{{ aap_configuration_filetree_create_secure_logging | default(true) }}"
      when: aap_oauthtoken is not defined
      tags:
        - always
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "https://{{ aap_hostname }}/api/gateway/v1/tokens/"
            user: "{{ aap_username }}"
            password: "{{ aap_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ aap_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            aap_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"

  roles:
    - infra.aap_configuration_extended.filetree_create

  post_tasks:
    - name: "Delete the Authentication Token used"
      ansible.builtin.uri:
        url: "https://{{ aap_hostname }}{{ aap_oauthtoken_url }}"
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ aap_validate_certs }}"
        status_code: 204
      when: aap_oauthtoken_url is defined
...
