---
controller_settings: []
#   - name: AUTH_LDAP_SERVER_URI
#     value: "ldap://idm.lab.example.com"
#   - name: AUTH_LDAP_BIND_DN
#     value: "{{ vault_ldap_bind_dn | default('uid=controller-binddn,cn=sysaccounts,cn=etc,dc=bcnconsulting,dc=com') }}"
#   - name: AUTH_LDAP_BIND_PASSWORD
#     value: "{{ vault_ldap_bind_password | default('password') }}"
#   - name: AUTH_LDAP_START_TLS
#     value: false
#   - name: AUTH_LDAP_USER_DN_TEMPLATE
#     value: ""
#   - name: AUTH_LDAP_CONNECTION_OPTIONS
#     value:
#       OPT_REFERRALS: 0
#       OPT_NETWORK_TIMEOUT: 30
#   - name: AUTH_LDAP_USER_SEARCH
#     value: [ "cn=users,cn=accounts,dc=bcnconsulting,dc=com", "SCOPE_SUBTREE","(uid=%(user)s)" ]
#   - name: AUTH_LDAP_USER_DN_TEMPLATE
#     value: ""
#   - name: AUTH_LDAP_USER_ATTR_MAP
#     value: { "first_name": "givenName", "last_name": "sn", "email": "mail" }
#   - name: AUTH_LDAP_GROUP_SEARCH
#     value: [ "cn=groups,cn=accounts,dc=bcnconsulting,dc=com","SCOPE_SUBTREE","(objectClass=posixgroup)" ]
#   - name: AUTH_LDAP_GROUP_TYPE
#     value: "NestedGroupOfNamesType"
#   - name: AUTH_LDAP_GROUP_TYPE_PARAMS
#     value: {"name_attr": "cn"}
#   - name: AUTH_LDAP_REQUIRE_GROUP
#     value: ""
#   - name: AUTH_LDAP_DENY_GROUP
#     value: ""
#   - name: AUTH_LDAP_USER_FLAGS_BY_GROUP
#     value: {"is_superuser": ["cn=controller-admins,cn=groups,cn=accounts,dc=bcnconsulting,dc=com"], "is_system_auditor": ["cn=team-ldap-auditor,cn=groups,cn=accounts,dc=bcnconsulting,dc=com"]}
...
