---
controller_hosts:
  - name: host1
    description: !unsafe
    inventory: Recursive Workflows Inventory
    variables:
      ansible_connection: local
      ansible_python_interpreter: !unsafe '{{ ansible_playbook_python }}'
  - name: host2
    description: !unsafe
    inventory: Recursive Workflows Inventory
    variables:
      ansible_connection: local
      ansible_python_interpreter: !unsafe '{{ ansible_playbook_python }}'
  - name: localhost
    description: !unsafe
    inventory: Recursive Workflows Inventory
    variables:
      ansible_connection: local
      ansible_python_interpreter: !unsafe '{{ ansible_playbook_python }}'
...
