---
controller_settings:
  # - name: AWX_ISOLATION_SHOW_PATHS
  #   value: "['/tmp', '/mnt/backup']"
  - name: DEFAULT_PROJECT_UPDATE_TIMEOUT
    value: 0
  - name: DEFAULT_INVENTORY_UPDATE_TIMEOUT
    value: 0
  - name: DEFAULT_JOB_TIMEOUT
    value: 0
  - name: MAX_FORKS
    value: 200
...
